USE [HotelsDB]
GO
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','0','2','14762 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','4','0','3244 DA','18')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','1','6','857 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','2','8','2210 DA','11')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','2','11178 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','1','8','21837 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','0','5','11796 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','0','7','27496 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','2','2','17115 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','1','7','4639 DA','28')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','0','3','26161 DA','28')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','0','8','9421 DA','28')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','0','6','20676 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','1','9','28943 DA','10')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','1','5','23533 DA','15')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','2','7','21655 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','3','5','20057 DA','25')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','2','6','11293 DA','5')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','2','9','2203 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','4','4','26394 DA','10')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','4','6','12363 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','0','27820 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','8','19627 DA','25')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','4','9','18355 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','3','9','18123 DA','19')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','7','6807 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','3','1','26326 DA','9')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','1','2','25889 DA','19')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','1','0','6635 DA','23')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','0','1','13914 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','2','1','8728 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','2','3','4286 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','2','7','12065 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','4','8','18960 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','1','3','2074 DA','14')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','1','8','23324 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','4','5','13800 DA','15')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','4','2','21851 DA','21')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','4','4','3066 DA','18')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','2','9','299 DA','28')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','3','8','25140 DA','26')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','0','4','4367 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','3','6','11226 DA','18')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','2','9','28630 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','2','8','26674 DA','14')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','1','3','23592 DA','11')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','2','8','25985 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','0','3','19470 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','4','0','8089 DA','1')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','3','2','4666 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','4','14130 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite','Chambre de type..','3','9','20112 DA','13')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','1','8','12273 DA','9')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','7','26728 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','4','0','27415 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Suite Luxe','Chambre de type..','3','3','2496 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Luxe','Chambre de type..','0','5','3102 DA','25')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','3','9','9965 DA','12')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','2','0','9785 DA','25')
GO