USE [HotelsDB]
GO
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','3','3','29989 DA','14')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','3','4','23345 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','5','28905 DA','29')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','2','0','25362 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','4','3','25447 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','5','12552 DA','29')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','4','6','17066 DA','5')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','3','1','3990 DA','15')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','1','9','4381 DA','26')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','2','4','1518 DA','26')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','2','2','11880 DA','7')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','2','6','3537 DA','21')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','2','3','8686 DA','13')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','4','5','21571 DA','5')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','4','7','753 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','0','0','13171 DA','19')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite Luxe','Chambre de type..','4','0','19690 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite Luxe','Chambre de type..','4','5','25787 DA','29')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','1','4','10438 DA','21')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','3','6','27126 DA','17')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','0','5','20403 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','7','12398 DA','15')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','0','6','6863 DA','1')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','0','2','22556 DA','20')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','3','7','12372 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','4','6','17193 DA','9')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','2','9','11433 DA','25')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','0','5','2932 DA','26')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','0','1','18751 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','4','3','9972 DA','1')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','2','6','15120 DA','7')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','4','1','1754 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','0','6','5316 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','4','22929 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','3','15448 DA','9')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','4','9','13226 DA','6')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','3','7','21964 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','0','3','4925 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','4','2','310 DA','27')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite Luxe','Chambre de type..','3','3','10960 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','1','5','22196 DA','13')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','3','4','4774 DA','28')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','0','4','12364 DA','15')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','4','4','1214 DA','22')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','1','3','17717 DA','8')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','3','0','20697 DA','13')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','2','9','4034 DA','12')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Lixe','Chambre de type..','0','3','9371 DA','23')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','4','7','7488 DA','0')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','4','7','14838 DA','23')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','1','5','3889 DA','3')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','1','9','7813 DA','23')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','1','5','11128 DA','25')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','3','2','26402 DA','23')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Swite','Chambre de type..','0','5','12633 DA','29')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double','Chambre de type..','2','1','24755 DA','2')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Simple','Chambre de type..','0','8','21689 DA','16')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Triple','Chambre de type..','2','4','23465 DA','12')
INSERT INTO [dbo].[HotelRooms] ([RoomType],[Description],[NbPersonnes],[NbRooms],[Price] ,[Hotel_HotelID]) VALUES  ( 'Double Supreme','Chambre de type..','3','2','4147 DA','3')
GO